CREATE TABLE APP.CLIENTLOGS (
	LOG_ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
	HASH VARCHAR(10) NOT NULL,
	DATE BIGINT NOT NULL,
	USER_ID INTEGER NOT NULL,
	PRIMARY KEY (LOG_ID)
);

CREATE UNIQUE INDEX APP.UNIQ_HASH ON APP.CLIENTLOGS (HASH);

CREATE TABLE APP.PLUGINLOGS (
	LOG_ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
	USER_ID INTEGER NOT NULL,
	TEST_RESULT VARCHAR(15) NOT NULL,
	START_TIME BIGINT,
	END_TIME BIGINT,
	PRIMARY KEY (LOG_ID)
);

CREATE TABLE APP.USERS (
	USER_ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
	USER_NAME VARCHAR(40) NOT NULL,
	PRIMARY KEY (USER_ID)
);

INSERT INTO APP.USERS(USER_NAME) VALUES ('Markiyan Matviyiv');
INSERT INTO APP.USERS(USER_NAME) VALUES ('Babichok');